version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/myapp
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - bundle
  bundle:
    # 'image' will vary depending on your docker-compose 
    # project name. You may need to run `docker-compose build web`
    # before this works.
    image: retrails5api_web
    command: echo 'Im a little data container short and stout...'
    volumes:
      - /bundle